// Package schemas
// Code generated by ikaiguang. <https://github.com/ikaiguang>
package schemas

import (
	migrationuitl "github.com/ikaiguang/go-srv-kit/data/migration"
	datatypes "gorm.io/datatypes"
	gorm "gorm.io/gorm"
	time "time"
)

var _ = time.Time{}

var _ = datatypes.JSON{}

// UserConfirmCodeSchema UserConfirmCode
var UserConfirmCodeSchema UserConfirmCode

// NewUserConfirmCode new schema
func NewUserConfirmCode() *UserConfirmCode {
	return &UserConfirmCode{}
}

const (
	TableName = "as_user_confirm_code"

	FieldId            = "id"
	FieldCreatedTime   = "created_time"
	FieldUpdatedTime   = "updated_time"
	FieldUserIdentify  = "user_identify"
	FieldConfirmType   = "confirm_type"
	FieldConfirmCode   = "confirm_code"
	FieldConfirmStatus = "confirm_status"
	FieldConfirmTime   = "confirm_time"
	FieldCancelTime    = "cancel_time"
)

// UserConfirmCode ENGINE InnoDB CHARSET utf8mb4 COMMENT '用户验证码确认表'
type UserConfirmCode struct {
	Id            uint64    `gorm:"column:id;primaryKey;type:uint;autoIncrement;comment:ID" json:"id"`
	CreatedTime   time.Time `gorm:"column:created_time;type:time;not null;comment:创建时间" json:"created_time"`
	UpdatedTime   time.Time `gorm:"column:updated_time;type:time;not null;comment:最后修改时间" json:"updated_time"`
	UserIdentify  string    `gorm:"column:user_identify;index;type:string;size:255;not null;default:'';comment:用户标识；手机、邮箱、。。。" json:"user_identify"`
	ConfirmType   uint32    `gorm:"column:confirm_type;type:uint;not null;default:0;comment:确认方式；1：邮箱，2：手机，3：密码，。。。" json:"confirm_type"`
	ConfirmCode   string    `gorm:"column:confirm_code;type:string;size:255;not null;default:'';comment:验证码" json:"confirm_code"`
	ConfirmStatus uint32    `gorm:"column:confirm_status;type:uint;not null;default:0;comment:确认状态；0：未指定，1：确认中，2：已确认，3：已过期，2：已取消" json:"confirm_status"`
	ConfirmTime   uint64    `gorm:"column:confirm_time;type:uint;not null;default:0;comment:确认时间" json:"confirm_time"`
	CancelTime    uint64    `gorm:"column:cancel_time;type:uint;not null;default:0;comment:取消时间" json:"cancel_time"`
}

// TableName table name
func (s *UserConfirmCode) TableName() string {
	return TableName
}

// CreateTableMigrator create table migrator
func (s *UserConfirmCode) CreateTableMigrator(migrator gorm.Migrator) migrationuitl.MigrationInterface {
	return migrationuitl.NewCreateTable(migrator, migrationuitl.Version, s)
}

// DropTableMigrator create table migrator
func (s *UserConfirmCode) DropTableMigrator(migrator gorm.Migrator) migrationuitl.MigrationInterface {
	return migrationuitl.NewDropTable(migrator, migrationuitl.Version, s)
}

// TableSQL table SQL
func (s *UserConfirmCode) TableSQL() string {
	return `
CREATE TABLE as_user_confirm_code (
	id bigint unsigned auto_increment comment 'ID',
	created_time datetime(3) NOT NULL comment '创建时间',
	updated_time datetime(3) NOT NULL comment '最后修改时间',
	user_identify varchar(255) NOT NULL DEFAULT '' comment '用户标识；手机、邮箱、。。。',
	confirm_type integer unsigned NOT NULL DEFAULT 0 comment '确认方式；1：邮箱，2：手机，3：密码，。。。',
	confirm_code varchar(255) NOT NULL DEFAULT '' comment '验证码',
	confirm_status integer unsigned NOT NULL DEFAULT 0 comment '确认状态；0：未指定，1：确认中，2：已确认，3：已过期，2：已取消',
	confirm_time bigint unsigned NOT NULL DEFAULT 0 comment '确认时间',
	cancel_time bigint unsigned NOT NULL DEFAULT 0 comment '取消时间',
	PRIMARY KEY (id),
	key (user_identify)
) ENGINE InnoDB,
  CHARSET utf8mb4,
  COMMENT '用户验证码确认表'
`
}
