// Package datarepos
// Code generated by ikaiguang. <https://github.com/ikaiguang>
package datarepos

import (
	context "context"
	"database/sql"
	"github.com/go-micro-saas/account-service/app/account-service/internal/data/po"
	gormpkg "github.com/ikaiguang/go-srv-kit/data/gorm"
)

// UserVerifyCodeDataRepo repo
type UserVerifyCodeDataRepo interface {
	NewTransaction(ctx context.Context, opts ...*sql.TxOptions) gormpkg.TransactionInterface
	Create(ctx context.Context, dataModel *po.UserVerifyCode) error
	ExistCreate(ctx context.Context, dataModel *po.UserVerifyCode) (anotherModel *po.UserVerifyCode, isNotFound bool, err error)
	CreateInBatches(ctx context.Context, dataModels []*po.UserVerifyCode, batchSize int) error
	Insert(ctx context.Context, dataModels []*po.UserVerifyCode) error
	Update(ctx context.Context, dataModel *po.UserVerifyCode) error
	UpdateVerifyStatus(ctx context.Context, dataModel *po.UserVerifyCode) (err error)
	ExistUpdate(ctx context.Context, dataModel *po.UserVerifyCode) (anotherModel *po.UserVerifyCode, isNotFound bool, err error)
	QueryOneById(ctx context.Context, id interface{}) (dataModel *po.UserVerifyCode, isNotFound bool, err error)
	QueryOneVerifyCode(ctx context.Context, param *po.GetVerifyCodeParam) (dataModel *po.UserVerifyCode, isNotFound bool, err error)
	QueryOneByConditions(ctx context.Context, conditions map[string]interface{}) (dataModel *po.UserVerifyCode, isNotFound bool, err error)
	QueryAllByConditions(ctx context.Context, conditions map[string]interface{}) (dataModels []*po.UserVerifyCode, err error)
	List(ctx context.Context, conditions map[string]interface{}, paginatorArgs *gormpkg.PaginatorArgs) (dataModels []*po.UserVerifyCode, totalNumber int64, err error)
	Delete(ctx context.Context, dataModel *po.UserVerifyCode) error
	DeleteByIds(ctx context.Context, ids interface{}) error
}
