// Package datarepos
// Code generated by ikaiguang. <https://github.com/ikaiguang>
package datarepos

import (
	context "context"
	"database/sql"
	"github.com/go-micro-saas/account-service/app/account-service/internal/data/po"
	gormpkg "github.com/ikaiguang/go-srv-kit/data/gorm"
)

// UserConfirmCodeDataRepo repo
type UserConfirmCodeDataRepo interface {
	NewTransaction(ctx context.Context, opts ...*sql.TxOptions) gormpkg.TransactionInterface
	Create(ctx context.Context, dataModel *po.UserConfirmCode) error
	ExistCreate(ctx context.Context, dataModel *po.UserConfirmCode) (anotherModel *po.UserConfirmCode, isNotFound bool, err error)
	CreateInBatches(ctx context.Context, dataModels []*po.UserConfirmCode, batchSize int) error
	Insert(ctx context.Context, dataModels []*po.UserConfirmCode) error
	Update(ctx context.Context, dataModel *po.UserConfirmCode) error
	ExistUpdate(ctx context.Context, dataModel *po.UserConfirmCode) (anotherModel *po.UserConfirmCode, isNotFound bool, err error)
	QueryOneById(ctx context.Context, id interface{}) (dataModel *po.UserConfirmCode, isNotFound bool, err error)
	QueryOneByConditions(ctx context.Context, conditions map[string]interface{}) (dataModel *po.UserConfirmCode, isNotFound bool, err error)
	QueryAllByConditions(ctx context.Context, conditions map[string]interface{}) (dataModels []*po.UserConfirmCode, err error)
	List(ctx context.Context, conditions map[string]interface{}, paginatorArgs *gormpkg.PaginatorArgs) (dataModels []*po.UserConfirmCode, totalNumber int64, err error)
	Delete(ctx context.Context, dataModel *po.UserConfirmCode) error
	DeleteByIds(ctx context.Context, ids interface{}) error
}
