// Package datarepos
// Code generated by ikaiguang. <https://github.com/ikaiguang>
package datarepos

import (
	context "context"
	"github.com/go-micro-saas/account-service/app/account-service/internal/data/po"
	gormpkg "github.com/ikaiguang/go-srv-kit/data/gorm"
)

// UserEventHistoryRepo repo
type UserEventHistoryRepo interface {
	Create(ctx context.Context, dataModel *po.UserEventHistory) error
	ExistCreate(ctx context.Context, dataModel *po.UserEventHistory) (anotherModel *po.UserEventHistory, isNotFound bool, err error)
	CreateInBatches(ctx context.Context, dataModels []*po.UserEventHistory, batchSize int) error
	Insert(ctx context.Context, dataModels []*po.UserEventHistory) error
	Update(ctx context.Context, dataModel *po.UserEventHistory) error
	ExistUpdate(ctx context.Context, dataModel *po.UserEventHistory) (anotherModel *po.UserEventHistory, isNotFound bool, err error)
	QueryOneById(ctx context.Context, id interface{}) (dataModel *po.UserEventHistory, isNotFound bool, err error)
	QueryOneByConditions(ctx context.Context, conditions map[string]interface{}) (dataModel *po.UserEventHistory, isNotFound bool, err error)
	QueryAllByConditions(ctx context.Context, conditions map[string]interface{}) (dataModels []*po.UserEventHistory, err error)
	List(ctx context.Context, conditions map[string]interface{}, paginatorArgs *gormpkg.PaginatorArgs) (dataModels []*po.UserEventHistory, totalNumber int64, err error)
	Delete(ctx context.Context, dataModel *po.UserEventHistory) error
	DeleteByIds(ctx context.Context, ids interface{}) error
}
