// Package datarepos
// Code generated by ikaiguang. <https://github.com/ikaiguang>
package datarepos

import (
	context "context"
	"github.com/go-micro-saas/admin-service/app/admin-service/internal/data/po"
	gormpkg "github.com/ikaiguang/go-srv-kit/data/gorm"
)

// AdminEventHistoryRepo repo
type AdminEventHistoryRepo interface {
	Create(ctx context.Context, dataModel *po.AdminEventHistory) error
	ExistCreate(ctx context.Context, dataModel *po.AdminEventHistory) (anotherModel *po.AdminEventHistory, isNotFound bool, err error)
	CreateInBatches(ctx context.Context, dataModels []*po.AdminEventHistory, batchSize int) error
	Insert(ctx context.Context, dataModels []*po.AdminEventHistory) error
	Update(ctx context.Context, dataModel *po.AdminEventHistory) error
	ExistUpdate(ctx context.Context, dataModel *po.AdminEventHistory) (anotherModel *po.AdminEventHistory, isNotFound bool, err error)
	QueryOneById(ctx context.Context, id interface{}) (dataModel *po.AdminEventHistory, isNotFound bool, err error)
	QueryOneByConditions(ctx context.Context, conditions map[string]interface{}) (dataModel *po.AdminEventHistory, isNotFound bool, err error)
	QueryAllByConditions(ctx context.Context, conditions map[string]interface{}) (dataModels []*po.AdminEventHistory, err error)
	List(ctx context.Context, conditions map[string]interface{}, paginatorArgs *gormpkg.PaginatorArgs) (dataModels []*po.AdminEventHistory, totalNumber int64, err error)
	Delete(ctx context.Context, dataModel *po.AdminEventHistory) error
	DeleteByIds(ctx context.Context, ids interface{}) error
}
