version: '3'

services:
  dev-admin-service:
    image: admin-service:latest
    container_name: dev-admin-service
    ports:
      - "10401:10401"
      - "10402:10402"
    networks:
      - my-network
    volumes:
      - dev_admin_service_data:/myworkspace/golang/src/workspace/runtime
      - ./configs:/myworkspace/golang/src/workspace/configs
    environment:
      TZ: Asia/Shanghai
    #entrypoint: ["/bin/bash"]
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:10401/api/v1/account/auth/ping" ]
      interval: 30s
      timeout: 5s
      retries: 3
    restart: unless-stopped

networks:
  my-network: # 已有的网络的名称
    external: true  # 标记为外部网络，表示这是已存在的网络

volumes:
  dev_admin_service_data:
    driver: local
