# encrypt 加密
encrypt:
  transfer_encrypt:
    public_key:
    private_key:
  service_encrypt:
    public_key:
    private_key:
  token_encrypt:
    sign_key: Ri13J8Itaqd4g6QMLZrDNCOoXhKjFmGy
    refresh_key: suzckjGdAqvgaBSJYCyDWVxihOeP7KR6
