// Package schemas
// Code generated by ikaiguang. <https://github.com/ikaiguang>
package schemas

import (
	migrationuitl "github.com/ikaiguang/go-srv-kit/data/migration"
	datatypes "gorm.io/datatypes"
	gorm "gorm.io/gorm"
	time "time"
)

var _ = time.Time{}

var _ = datatypes.JSON{}

// UserVerifyCodeSchema UserVerifyCode
var UserVerifyCodeSchema UserVerifyCode

// NewUserVerifyCode new schema
func NewUserVerifyCode() *UserVerifyCode {
	return &UserVerifyCode{}
}

const (
	TableName = "bas_admin_verify_code"

	FieldId            = "id"
	FieldCreatedTime   = "created_time"
	FieldUpdatedTime   = "updated_time"
	FieldVerifyAccount = "verify_account"
	FieldVerifyType    = "verify_type"
	FieldVerifyCode    = "verify_code"
	FieldVerifyStatus  = "verify_status"
	FieldConfirmTime   = "confirm_time"
	FieldCancelTime    = "cancel_time"
)

// UserVerifyCode ENGINE InnoDB CHARSET utf8mb4 COMMENT '用户验证码确认表'
type UserVerifyCode struct {
	Id            uint64    `gorm:"column:id;primaryKey;type:uint;autoIncrement;comment:ID" json:"id"`
	CreatedTime   time.Time `gorm:"column:created_time;type:time;not null;comment:创建时间" json:"created_time"`
	UpdatedTime   time.Time `gorm:"column:updated_time;type:time;not null;comment:最后修改时间" json:"updated_time"`
	VerifyAccount string    `gorm:"column:verify_account;index;type:string;size:255;not null;default:'';comment:验证账户；手机、邮箱、。。。" json:"verify_account"`
	VerifyType    uint32    `gorm:"column:verify_type;type:uint;not null;default:0;comment:验证方式；1：邮箱，2：手机，3：密码，。。。" json:"verify_type"`
	VerifyCode    string    `gorm:"column:verify_code;type:string;size:255;not null;default:'';comment:验证码" json:"verify_code"`
	VerifyStatus  uint32    `gorm:"column:verify_status;type:uint;not null;default:0;comment:确认状态；0：未指定，1：确认中，2：已确认，3：已过期，2：已取消" json:"verify_status"`
	ConfirmTime   uint64    `gorm:"column:confirm_time;type:uint;not null;default:0;comment:确认时间" json:"confirm_time"`
	CancelTime    uint64    `gorm:"column:cancel_time;type:uint;not null;default:0;comment:取消时间" json:"cancel_time"`
}

// TableName table name
func (s *UserVerifyCode) TableName() string {
	return TableName
}

// CreateTableMigrator create table migrator
func (s *UserVerifyCode) CreateTableMigrator(migrator gorm.Migrator) migrationuitl.MigrationInterface {
	return migrationuitl.NewCreateTable(migrator, migrationuitl.Version, s)
}

// DropTableMigrator create table migrator
func (s *UserVerifyCode) DropTableMigrator(migrator gorm.Migrator) migrationuitl.MigrationInterface {
	return migrationuitl.NewDropTable(migrator, migrationuitl.Version, s)
}

// TableSQL table SQL
func (s *UserVerifyCode) TableSQL() string {
	return `
CREATE TABLE bas_admin_verify_code (
	id bigint unsigned auto_increment comment 'ID',
	created_time datetime(3) NOT NULL comment '创建时间',
	updated_time datetime(3) NOT NULL comment '最后修改时间',
	verify_account varchar(255) NOT NULL DEFAULT '' comment '验证账户；手机、邮箱、。。。',
	verify_type integer unsigned NOT NULL DEFAULT 0 comment '验证方式；1：邮箱，2：手机，3：密码，。。。',
	verify_code varchar(255) NOT NULL DEFAULT '' comment '验证码',
	verify_status integer unsigned NOT NULL DEFAULT 0 comment '确认状态；0：未指定，1：确认中，2：已确认，3：已过期，2：已取消',
	confirm_time bigint unsigned NOT NULL DEFAULT 0 comment '确认时间',
	cancel_time bigint unsigned NOT NULL DEFAULT 0 comment '取消时间',
	PRIMARY KEY (id),
	key (verify_account)
) ENGINE InnoDB,
  CHARSET utf8mb4,
  COMMENT '用户验证码确认表'
`
}
